
services:
  postgres:
    ports:
      - "5432:5432"

  mosquitto:
    ports:
      - "1883:1883"
      - "8883:8883"
      - "9001:9001"

  prometheus:
    ports:
      - "9090:9090"

  grafana:
    ports:
      - "3000:3000"

  discovery-server:
    ports:
      - "8761:8761"

  config-server:
    ports:
      - "8888:8888"

  api-gateway:
    ports:
      - "8080:8080"
      
  auth-service:
    ports:
      - "8081:8081"

  game-service:
    ports:
      - "8082:8082"
      
  tournament-service:
    ports:
      - "8083:8083"
      
  stats-service:
    ports:
      - "8084:8084"

  edge-sync-service:
    ports:
      - "8085:8085"
