server:
  port: 8085

spring:
  application:
    name: edge-sync-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

mqtt:
  broker-url: tcp://localhost:1883
  client-id: edge-sync-service-client
  username: 
  password: 
  default-topic: edge/+/events

logging:
  level:
    org.springframework.integration: DEBUG
