# Indirizzo del database PostgreSQL che abbiamo appena creato
spring.datasource.url=jdbc:postgresql://localhost:5432/bitpub_db

# Le credenziali del nuovo utente protetto
spring.datasource.username=bitpub_user
spring.datasource.password=bitpub2026

# Permette a JPA (Hibernate) di creare le tabelle nel DB automaticamente in base alle classi Java
spring.jpa.hibernate.ddl-auto=update

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Aggiungiamo questa riga per vedere nel terminale le query SQL eseguite (utilissimo per capire cosa succede sotto al cofano!)
spring.jpa.show-sql=true