# ==========================================
# CONFIGURAZIONE DATABASE POSTGRESQL
# ==========================================
# Indirizzo del database PostgreSQL che abbiamo appena creato
spring.datasource.url=jdbc:postgresql://localhost:5433/bitpub_db

# Le credenziali del nuovo utente protetto
spring.datasource.username=bitpub_user
spring.datasource.password=bitpub2026

# Permette a JPA (Hibernate) di creare le tabelle nel DB automaticamente in base alle classi Java
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Aggiungiamo questa riga per vedere nel terminale le query SQL eseguite (utilissimo per capire cosa succede sotto al cofano!)
spring.jpa.show-sql=true

# ==========================================
# CONFIGURAZIONE FLYWAY (MIGRAZIONI DB)
# ==========================================
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true

# ==========================================
# CONFIGURAZIONE SICUREZZA E JWT
# ==========================================
# Chiave segreta utilizzata per firmare e validare i token JWT.
jwt.secret=UnaChiaveSegretaMoltoLungaPerGarantireSicurezzaBitPub2026!
jwt.expiration=86400000

# ==========================================
# CONFIGURAZIONE SERIALIZZAZIONE (JACKSON)
# ==========================================
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone=Europe/Rome

# ==========================================
# CONFIGURAZIONE MQTT TLS (mTLS)
# ==========================================
# Valori di default locali. Se l'app gira in Cloud/Docker, leggerà le variabili d'ambiente (es. MQTT_CA_PATH)
mqtt.tls.ca-path=${MQTT_CA_PATH:./certs/ca.crt}
mqtt.tls.client-crt-path=${MQTT_CLIENT_CRT_PATH:./certs/client.crt}
mqtt.tls.client-key-path=${MQTT_CLIENT_KEY_PATH:./certs/client.key}
mqtt.tls.keystore-password=${MQTT_KEYSTORE_PASSWORD:bitpub2026}