# Indirizzo del database PostgreSQL (assumendo che sia installato sul tuo computer per lo sviluppo)
spring.datasource.url=jdbc:postgresql://localhost:5432/bitpub_db
spring.datasource.username=postgres
spring.datasource.password=tua_password_segreta

# Permette a JPA di creare le tabelle nel DB automaticamente in base alle classi Java che scriveremo
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect