server:
  port: 8085

spring:
  application:
    name: demo-control-panel
  jackson:
    serialization:
      write-dates-as-timestamps: false

mqtt:
  broker:
    url: tcp://localhost:1883
  client-id: demo-control-panel-publisher
