# =================================================================
# Configurazione di Sicurezza TLS per Mosquitto - Progetto BitPub
# =================================================================

# 1. Impostiamo la porta di ascolto sicura (MQTTS)
listener 8883

# 2. Blocchiamo categoricamente le connessioni anonime
allow_anonymous false

# 3. Indichiamo a Mosquitto dove trovare i certificati generati da Stefano e Luca.
# 3. Indichiamo a Mosquitto dove trovare i certificati generati da Stefano e Luca.
cafile /etc/mosquitto/certs/ca.crt
certfile /etc/mosquitto/certs/broker.crt
keyfile /etc/mosquitto/certs/broker.key

# 4. IL GUARDIANO: Obblighiamo chiunque si connetta (i Simulatori/Edge)
# a presentare un certificato firmato dalla nostra CA aziendale (ca.crt)
require_certificate true

# 5. (Opzionale ma consigliato) Protocollo di sicurezza minimo
tls_version tlsv1.2