server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://auth-service:8081
          predicates:
            - Path=/api/v1/auth/**
            
        - id: user-service
          uri: http://user-service:8082
          predicates:
            - Path=/api/v1/users/**
          filters:
            - name: JwtAuthenticationFilter

        - id: locale-service
          uri: http://locale-service:8083
          predicates:
            - Path=/api/v1/locales/**
          filters:
            - name: JwtAuthenticationFilter
            
        - id: game-catalog-service
          uri: http://game-catalog-service:8084
          predicates:
            - Path=/api/v1/catalog/**
          filters:
            - name: JwtAuthenticationFilter

        - id: match-service
          uri: http://match-service:8085
          predicates:
            - Path=/api/matches/**

        - id: tournament-service
          uri: http://tournament-service:8086
          predicates:
            - Path=/api/v1/tournaments/**

        - id: statistics-service
          uri: http://statistics-service:8087
          predicates:
            - Path=/api/v1/statistics/**

bitpub:
  jwt:
    secret: 1234567890123456789012345678901234567890123456789012345678901234
    expirationMs: 86400000
