package com.bitpub.common.security.enums;

public enum Permission {
    MATCH_READ_SELF,
    STATS_READ_SELF,
    TOURNAMENT_JOIN,
    PROFILE_UPDATE_SELF,
    GAME_MANAGE_LOCAL,
    MATCH_MANAGE_LOCAL,
    EDGE_MANAGE_LOCAL,
    USERS_READ_LOCAL,
    STATS_READ_LOCAL,
    GAME_TYPE_CREATE,
    GAME_TYPE_UPDATE,
    SENSOR_CONFIG_MANAGE,
    TOURNAMENT_MANAGE_GLOBAL,
    USERS_MANAGE_GLOBAL,
    SYSTEM_CONFIG,
    GLOBAL_STATS_READ,
    ROLE_MANAGE,
    PLATFORM_MONITORING
}
